/**
 * @description       : A class for Constants
 * @author            : Rodrigo Balbi - Oktana
 * @group             : 
 * @last modified on  : 05-05-2022
 * @last modified by  : Rodrigo Balbi - Oktana
**/
global with sharing class Constants {
    global static final String ANIMAL_LION = 'Lion';
    global static final String ANIMAL_CAT = 'Cat';
    global static final String ANIMAL_HORSE = 'Horse';
    global static final String ANIMAL_ALLIGATOR = 'Alligator';
    global static final String ANIMAL_BEAR = 'Bear';
    global static final String ANIMAL_COW = 'Cow';
    global static final String ANIMAL_DOG = 'Dog';
    global static final String WOOD_TYPE_STANDARD = 'Standard';
    global static final String WOOD_TYPE_RECYCLED = 'Recycled';
}